# Generated by Django 5.1.1 on 2024-10-05 02:53

import django.core.validators
import frutipedia.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), frutipedia.profiles.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), frutipedia.profiles.validators.validate_name]),
        ),
    ]
